language: python
python: "2.7"
sudo: false
cache:
  directories:
  - eggs
addons:
  firefox: latest-esr
install:
- python bootstrap-buildout.py
- bin/buildout -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_script:
- pkill -9 firefox
notifications:
  irc:
    channels:
      - irc.freenode.org#operun
      on_success: change
      on_failure: always
